
# This file is part of the dinLanguagePlugin package.
# (c) DineCat, 2010 http://dinecat.com/
#
# For the full copyright and license information, please view the LICENSE file,
# that was distributed with this package, or see http://www.dinecat.com/din/license.html

# dinLanguagePlugin cache routing configuration
#
# @package     dinLanguagePlugin
# @subpackage  config
# @author      Nicolay N. Zyk <relo.san@gmail.com>

routes:
    dictionary_choices:
        type:                   'choices'
        get:
            model:              'DinLanguageDictionary'
            method:             'getChoicesQuery'
            path:               ':_root/DinLanguageDictionary/dictionary_choices'
            key:                ':_i18n'
        remove:
            default:
                path:           ':_root/DinLanguageDictionary/dictionary_choices'
                key:            '*'

    lang_choices:
        type:                   'choices'
        get:
            model:              'DinLanguageBindApplication'
            method:             'getAppLanguagesQuery'
            path:               ':_root/DinLanguageBindApplication/lang_choices'
            key:                ':application.:_i18n'
        remove:
            default:
                path:           ':_root/DinLanguageBindApplication/lang_choices'
                key:            '*'

links:
    DinLanguageBindApplication: ['lang_choices']
    DinLanguageDictionary:      ['dictionary_choices']
    DinLanguageDictionaryPair:  ['dictionary_choices']

#EOF