
# This file is part of the dinLanguagePlugin package.
# (c) DineCat, 2010 http://dinecat.com/
#
# For the full copyright and license information, please view the LICENSE file,
# that was distributed with this package, or see http://www.dinecat.com/din/license.html

# dinLanguagePlugin model configuration
#
# @package     dinLanguagePlugin
# @subpackage  config
# @author      Nicolay N. Zyk <relo.san@gmail.com>
models:

    DinLanguageGroup:
        disable:                true

    DinLanguageBindGroup:
        disable:                true

forms:
    DinLanguageDictionaryPair:
        fields:
            dictionary_id:
                widget:
                    class:          'sfWidgetFormInputHidden'
                    options:
                        model:      null
                        add_empty:  null
                        label:      null

filters:

    DinLanguageBindApplication:
        disable:                true

    DinLanguageBindGroup:
        disable:                true

    DinLanguageBindGroupTranslation:
        disable:                true

    DinLanguageTranslation:
        disable:                true

    DinLanguageDictionaryTranslation:
        disable:                true

    DinLanguageDictionaryPairTranslation:
        disable:                true

    DinLanguageGroupTranslation:
        disable:                true

#EOF