
# This file is part of the dinLanguagePlugin package.
# (c) DineCat, 2010 http://dinecat.com/
#
# For the full copyright and license information, please view the LICENSE file,
# that was distributed with this package, or see http://www.dinecat.com/din/license.html

# dinLangDictionaryAdmin module generator configuration
#
# @package     dinLanguagePlugin
# @subpackage  modules.dinLangDictionaryAdmin.config
# @author      Nicolay N. Zyk <relo.san@gmail.com>

plugin:                             'dinLanguagePlugin'

generator:

    param:

        model_class:                'DinLanguageDictionary'
        singular:                   null
        plural:                     null
        route_prefix:               'din_lang_dictionary_admin'
        with_doctrine_route:        true
        i18n_catalogue:             'dinLangDictionaryAdmin'

        config:

            actions:                null

            fields:
                application:        { label: 'fieldLabels.application' }
                name:               { label: 'fieldLabels.name' }
                title:              { label: 'fieldLabels.title' }
                description:        { label: 'fieldLabels.description' }

            list:
                title:              'titles.list'
                display:            ['application', 'title']
                table_method:       'retrieveWithI18n'
                pager_class:        'dinDoctrinePager'
                actions:
                    _new:
                        params:     { ajax: 'action' }
                object_actions:
                    pairs:
                        label:      'listLabels.pairs'
                        action:     'pairs'
                        icon_class_suffix:  'document'
                        params:     { ajax: 'action' }
                    _edit:
                        params:     { ajax: 'action' }
                    _delete:
                        params:     { ajax: 'post' }
                sort:
                    application:    { columns: ['application'] }
                    title:          { columns: ['application', 'title'] }

            filter:
                display:            ['application', 'name', 'title', 'description']

            form:
                display:
                    fieldsets.base: ['application', 'name', 'title', 'description']

            edit:
                title:              'titles.edit.%%title%%'
                actions:
                    _delete:
                        params:     { ajax: 'action' }
                    _save:          null
                    _list:
                        params:     { ajax: 'action' }

            new:
                title:              'titles.new'
                actions:
                    _save_and_add:  null
                    _save:          null
                    _list:
                        params:     { ajax: 'action' }

            show:                   null

#EOF